In [38]:
import sklearn

In [39]:
sklearn.__version__

'1.2.1'

In [40]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
import pandas as pd
from sklearn.metrics import accuracy_score

In [41]:
print(load_iris().DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [42]:
iris = load_iris()
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [43]:
type(iris)

sklearn.utils._bunch.Bunch

In [44]:
iris.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [45]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [46]:
iris.data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [47]:
iris_df = pd.DataFrame(data= iris.data,
                       columns=iris.feature_names)

In [48]:
iris_df['label'] = iris.target
iris_df.head(3)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   

   label  
0      0  
1      0  
2      0

In [49]:
x_train, x_test, y_train, y_test = train_test_split(iris.data,
                                                    iris.target,
                                                    test_size=0.2,
                                                    random_state=11)

In [50]:
df_clf = DecisionTreeClassifier(random_state=11)
df_clf.fit(x_train, y_train)
pred = df_clf.predict(x_test)
accuracy_score(y_test, pred)

0.9333333333333333

In [51]:
pred

array([2, 2, 1, 1, 2, 0, 1, 0, 0, 1, 1, 1, 1, 2, 2, 0, 2, 1, 2, 2, 1, 0,
       0, 1, 0, 0, 2, 1, 0, 1])

In [52]:
y_test

array([2, 2, 2, 1, 2, 0, 1, 0, 0, 1, 2, 1, 1, 2, 2, 0, 2, 1, 2, 2, 1, 0,
       0, 1, 0, 0, 2, 1, 0, 1])

In [53]:
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [54]:
dt_clf = DecisionTreeClassifier()
dt_clf.fit(iris.data, iris.target)
pred = dt_clf.predict(iris.data)
accuracy_score(iris.target, pred)

1.0

In [55]:
x_train, x_test, y_train, y_test = train_test_split(iris.data,
                                                    iris.target,
                                                    test_size=0.3,
                                                    random_state=None)

In [56]:
df_clf = DecisionTreeClassifier(random_state=None)
df_clf.fit(x_train, y_train)
pred = df_clf.predict(x_test)
accuracy_score(y_test, pred)

0.9333333333333333

In [57]:
#KFold

In [58]:
from sklearn.model_selection import KFold
import numpy as np


In [59]:
iris = load_iris()
df_clf = DecisionTreeClassifier(random_state=156)

In [60]:
kfold = KFold(n_splits=5, shuffle=True, random_state=156)
cv_accuracy = []
n_iter = 0
for train_index, test_index in kfold.split(iris.data):
    # print(train_index)
    # print(test_index)
    x_train, x_test = iris.data[train_index], iris.data[test_index]
    # print(x_test)
    y_train, y_test = iris.target[train_index], iris.target[test_index]
    # print(y_test)
    dt_clf.fit(x_train, y_train)
    pred = dt_clf.predict(x_test)
    n_iter += 1
    accuracy =  np.round(accuracy_score(y_test, pred), 4)
    train_size = x_train.shape[0]
    test_size = x_test.shape[0]
    print(f'{n_iter} 교차 검증 정확도 : {accuracy}, 학습 데이터 크기 : {train_size}, 검증 데이터 크기 : {test_size}')
    print(f'검증데이터 인덱스 : {test_index}')
    cv_accuracy.append(accuracy)
print(f'평균 정확도 : {np.round(np.mean(cv_accuracy), 4)}')

1 교차 검증 정확도 : 1.0, 학습 데이터 크기 : 120, 검증 데이터 크기 : 30
검증데이터 인덱스 : [  0   5   8   9  12  28  29  30  32  50  51  57  74  76  87  89  95  98
 103 113 117 118 120 121 125 128 130 135 146 147]
2 교차 검증 정확도 : 0.9, 학습 데이터 크기 : 120, 검증 데이터 크기 : 30
검증데이터 인덱스 : [  6   7  19  21  22  31  33  47  53  59  68  69  71  72  77  79  82  90
  94  97  99 106 112 115 116 119 122 126 136 141]
3 교차 검증 정확도 : 0.9333, 학습 데이터 크기 : 120, 검증 데이터 크기 : 30
검증데이터 인덱스 : [  4  13  14  16  18  34  35  39  41  42  52  56  60  61  67  70  73  75
  80  85  88 105 107 131 133 134 140 142 144 149]
4 교차 검증 정확도 : 0.9667, 학습 데이터 크기 : 120, 검증 데이터 크기 : 30
검증데이터 인덱스 : [  1   3  15  20  24  25  26  37  40  45  46  54  65  84  86  92  96 101
 102 108 114 123 124 127 129 132 137 139 143 145]
5 교차 검증 정확도 : 0.9667, 학습 데이터 크기 : 120, 검증 데이터 크기 : 30
검증데이터 인덱스 : [  2  10  11  17  23  27  36  38  43  44  48  49  55  58  62  63  64  66
  78  81  83  91  93 100 104 109 110 111 138 148]
평균 정확도 : 0.9533


In [61]:
kfold = KFold(n_splits=3, shuffle=True)
n_iter = 0
for train_index, test_index in kfold.split(iris_df):
    n_iter += 1
    label_train = iris_df['label'].iloc[train_index]
    label_test = iris_df['label'].iloc[test_index]
    print(f'{n_iter} 교차검증')
    print(f'학습 레이블 데이터 분포 : \n{label_train.value_counts()}')
    print(f'검증 레이블 데이터 분포 : \n{label_test.value_counts()}')

1 교차검증
학습 레이블 데이터 분포 : 
2    36
0    32
1    32
Name: label, dtype: int64
검증 레이블 데이터 분포 : 
0    18
1    18
2    14
Name: label, dtype: int64
2 교차검증
학습 레이블 데이터 분포 : 
1    37
2    32
0    31
Name: label, dtype: int64
검증 레이블 데이터 분포 : 
0    19
2    18
1    13
Name: label, dtype: int64
3 교차검증
학습 레이블 데이터 분포 : 
0    37
2    32
1    31
Name: label, dtype: int64
검증 레이블 데이터 분포 : 
1    19
2    18
0    13
Name: label, dtype: int64


In [62]:
from sklearn.model_selection import StratifiedKFold

In [63]:
skfold = StratifiedKFold(n_splits=3, shuffle=False)
n_iter = 0
for train_index, test_index in skfold.split(iris_df, iris_df['label']):
    n_iter += 1
    label_train = iris_df['label'].iloc[train_index]
    label_test = iris_df['label'].iloc[test_index]
    print(f'{n_iter} 교차검증')
    print(f'학습 레이블 데이터 분포 : \n{label_train.value_counts()}')
    print(f'검증 레이블 데이터 분포 : \n{label_test.value_counts()}')

1 교차검증
학습 레이블 데이터 분포 : 
2    34
0    33
1    33
Name: label, dtype: int64
검증 레이블 데이터 분포 : 
0    17
1    17
2    16
Name: label, dtype: int64
2 교차검증
학습 레이블 데이터 분포 : 
1    34
0    33
2    33
Name: label, dtype: int64
검증 레이블 데이터 분포 : 
0    17
2    17
1    16
Name: label, dtype: int64
3 교차검증
학습 레이블 데이터 분포 : 
0    34
1    33
2    33
Name: label, dtype: int64
검증 레이블 데이터 분포 : 
1    17
2    17
0    16
Name: label, dtype: int64


In [64]:
skfold = StratifiedKFold(n_splits=3, shuffle=False)
n_iter = 0
cv_accuracy = []
for train_index, test_index in skfold.split(iris.data, iris.target):
    n_iter += 1
    x_train, x_test = iris.data[train_index], iris.data[test_index]
    y_train, y_test = iris.target[train_index], iris.target[test_index]
    dt_clf.fit(x_train, y_train)
    pred = dt_clf.predict(x_test)
    accuracy =  np.round(accuracy_score(y_test, pred), 4)
    train_size = x_train.shape[0]
    test_size = x_test.shape[0]
    print(f'{n_iter} 교차 검증 정확도 : {accuracy}, 학습 데이터 크기 : {train_size}, 검증 데이터 크기 : {test_size}')
    print(f'검증데이터 인덱스 : {test_index}')
    cv_accuracy.append(accuracy)
print(f'평균 정확도 : {np.round(np.mean(cv_accuracy), 4)}')

1 교차 검증 정확도 : 0.98, 학습 데이터 크기 : 100, 검증 데이터 크기 : 50
검증데이터 인덱스 : [  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  50
  51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66 100 101
 102 103 104 105 106 107 108 109 110 111 112 113 114 115]
2 교차 검증 정확도 : 0.94, 학습 데이터 크기 : 100, 검증 데이터 크기 : 50
검증데이터 인덱스 : [ 17  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  67
  68  69  70  71  72  73  74  75  76  77  78  79  80  81  82 116 117 118
 119 120 121 122 123 124 125 126 127 128 129 130 131 132]
3 교차 검증 정확도 : 0.98, 학습 데이터 크기 : 100, 검증 데이터 크기 : 50
검증데이터 인덱스 : [ 34  35  36  37  38  39  40  41  42  43  44  45  46  47  48  49  83  84
  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99 133 134 135
 136 137 138 139 140 141 142 143 144 145 146 147 148 149]
평균 정확도 : 0.9667


In [67]:
# 교차검증 cross_val_score()

In [66]:
from sklearn.model_selection import cross_val_score

In [77]:
df_clf = DecisionTreeClassifier(random_state=156)
cross_val_score(dt_clf,
                iris.data,
                iris.target,
                cv=3,
                scoring='accuracy',
                verbose=0)

array([0.98, 0.94, 0.98])

In [79]:
from sklearn.model_selection import GridSearchCV

In [86]:
x_train, x_test, y_train, y_test = train_test_split(iris.data,
                                                    iris.target,
                                                    test_size=0.2,
                                                    random_state=121)
dtree = DecisionTreeClassifier()
param = {'max_depth' : [1, 2, 3],
             'min_samples_split' : [2, 3]}

In [90]:

grid_tree = GridSearchCV(dtree,
                        param_grid=param,
                        cv=3,
                        refit=True)

In [92]:
grid_tree.fit(x_train, y_train)

GridSearchCV(cv=3, estimator=DecisionTreeClassifier(),
             param_grid={'max_depth': [1, 2, 3], 'min_samples_split': [2, 3]})

In [94]:
grid_tree.best_score_

0.975

In [96]:
grid_tree.best_params_

{'max_depth': 3, 'min_samples_split': 2}

In [98]:
grid_tree.best_index_

4

In [99]:
grid_tree.cv_results_

{'mean_fit_time': array([0.00033482, 0.00016785, 0.00066725, 0.00034451, 0.        ,
        0.00085624]),
 'std_fit_time': array([0.00047351, 0.00023737, 0.00047182, 0.00048722, 0.        ,
        0.00061614]),
 'mean_score_time': array([0.00033379, 0.00066916, 0.00049798, 0.        , 0.        ,
        0.00049138]),
 'std_score_time': array([0.00047204, 0.00023557, 0.00070425, 0.        , 0.        ,
        0.00069492]),
 'param_max_depth': masked_array(data=[1, 1, 2, 2, 3, 3],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'param_min_samples_split': masked_array(data=[2, 3, 2, 3, 2, 3],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'max_depth': 1, 'min_samples_split': 2},
  {'max_depth': 1, 'min_samples_split': 3},
  {'max_depth': 2, 'min_samples_split': 2},
  {'max_depth': 2, 'min_samples_split': 3},
  {'max_depth': 3, 'min_sample

In [102]:
df = pd.DataFrame(grid_tree.cv_results_)

In [103]:
df.columns

Index(['mean_fit_time', 'std_fit_time', 'mean_score_time', 'std_score_time',
       'param_max_depth', 'param_min_samples_split', 'params',
       'split0_test_score', 'split1_test_score', 'split2_test_score',
       'mean_test_score', 'std_test_score', 'rank_test_score'],
      dtype='object')

In [107]:
df[['params',
    'mean_test_score',
    'rank_test_score',
    'split0_test_score',
    'split1_test_score', 
    'split2_test_score']]

params  mean_test_score  rank_test_score  \
0  {'max_depth': 1, 'min_samples_split': 2}         0.700000                5   
1  {'max_depth': 1, 'min_samples_split': 3}         0.700000                5   
2  {'max_depth': 2, 'min_samples_split': 2}         0.958333                3   
3  {'max_depth': 2, 'min_samples_split': 3}         0.958333                3   
4  {'max_depth': 3, 'min_samples_split': 2}         0.975000                1   
5  {'max_depth': 3, 'min_samples_split': 3}         0.975000                1   

   split0_test_score  split1_test_score  split2_test_score  
0              0.700                0.7               0.70  
1              0.700                0.7               0.70  
2              0.925                1.0               0.95  
3              0.925                1.0               0.95  
4              0.975                1.0               0.95  
5              0.975                1.0               0.95

In [108]:
pred = grid_tree.predict(x_test)

In [109]:
accuracy_score(y_test, pred)

0.9666666666666667

In [112]:
pred = grid_tree.best_estimator_.predict(x_test)
accuracy_score(y_test, pred)

0.9666666666666667