In [1]:
import pandas as pd
import numpy as np

In [3]:
%precision 3

'%.3f'

In [4]:
pd.set_option('display.float_format', '{:.3f}'.format)
# pd.set_option('display.float_format', None)

In [7]:
df = pd.read_csv('data\ch2_scores_em.csv', index_col='student number')

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 50 entries, 1 to 50
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   english      50 non-null     int64
 1   mathematics  50 non-null     int64
dtypes: int64(2)
memory usage: 1.2 KB


In [9]:
np.__version__

'1.21.5'

In [10]:
pd.__version__

'1.4.4'

In [11]:
np.mean(df['english'])

58.380

In [13]:
scores = np.array(df['english'])[:10]
scores

array([42, 69, 56, 41, 57, 48, 65, 49, 65, 58], dtype=int64)

In [15]:
df['english'].values[:10]

array([42, 69, 56, 41, 57, 48, 65, 49, 65, 58], dtype=int64)

In [18]:
score_df = pd.DataFrame({'score' : scores}, index=pd.Index(['A','B','C','D','E','F','G','H','I','J'],
                                                name='student'))

In [19]:
score_df

score
student       
A           42
B           69
C           56
D           41
E           57
F           48
G           65
H           49
I           65
J           58

In [22]:
sum(scores)/len(scores)

55.0

In [23]:
sum(score_df['score'])/len(score_df['score'])

55.000

In [24]:
np.mean(scores)

55.0

In [25]:
np.mean(score_df['score'])

55.000

In [26]:
score_df['score'].mean()

55.000

In [27]:
score_df.mean()

score   55.000
dtype: float64

In [29]:
sorted_scores = np.sort(scores)
sorted_scores

array([41, 42, 48, 49, 56, 57, 58, 65, 65, 69], dtype=int64)

In [37]:
n = len(sorted_scores)
if n % 2 == 0:
    m0 = sorted_scores[n//2 -1]
    m1 = sorted_scores[n//2]
    median = (m0 + m1) / 2
else:
    median = sorted_scores[(n+1)/2-1]
median

56.5

In [38]:
np.median(scores)

56.5

In [39]:
score_df.median()

score   56.500
dtype: float64

In [40]:
score_df.mode()

score
0     65

In [41]:
pd.Series([1,1,2,2,3]).mode()

0    1
1    2
dtype: int64

In [42]:
mean = np.mean(scores)
mean

55.0

In [43]:
devlation = scores - mean
devlation

array([-13.,  14.,   1., -14.,   2.,  -7.,  10.,  -6.,  10.,   3.])

In [44]:
devlation.sum()

0.0

In [45]:
devlation.mean()

0.0

In [46]:
summary_df = score_df.copy()
summary_df['devlation'] = devlation
summary_df

score  devlation
student                  
A           42    -13.000
B           69     14.000
C           56      1.000
D           41    -14.000
E           57      2.000
F           48     -7.000
G           65     10.000
H           49     -6.000
I           65     10.000
J           58      3.000

In [47]:
summary_df.mean()

score       55.000
devlation    0.000
dtype: float64

In [48]:
np.mean(devlation**2)

86.0

In [51]:
np.var(scores,ddof=1)

95.55555555555556

In [52]:
score_df.var(ddof=0)

score   86.000
dtype: float64

In [53]:
summary_df['square of deviation'] = np.square(devlation)
summary_df

score  devlation  square of deviation
student                                       
A           42    -13.000              169.000
B           69     14.000              196.000
C           56      1.000                1.000
D           41    -14.000              196.000
E           57      2.000                4.000
F           48     -7.000               49.000
G           65     10.000              100.000
H           49     -6.000               36.000
I           65     10.000              100.000
J           58      3.000                9.000

In [54]:
summary_df.mean()

score                 55.000
devlation              0.000
square of deviation   86.000
dtype: float64

In [55]:
np.sqrt(np.var(scores, ddof=0))

9.273618495495704

In [56]:
np.std(scores, ddof=0)

9.273618495495704

In [59]:
score_df.std(ddof=0)

score   9.274
dtype: float64

In [60]:
np.max(scores) - np.min(scores)

28

In [64]:
scores_q1 = np.percentile(scores, 25)
scores_q2 = np.percentile(scores, 50)
scores_q3 = np.percentile(scores, 75)
scores_IQR = scores_q3 - scores_q1
scores_IQR,scores_q1,scores_q3, scores_q2

(15.0, 48.25, 63.25, 56.5)

In [65]:
score_df.describe()

score
count 10.000
mean  55.000
std    9.775
min   41.000
25%   48.250
50%   56.500
75%   63.250
max   69.000

In [66]:
z = (scores - np.mean(scores))/np.std(scores)
z

array([-1.402,  1.51 ,  0.108, -1.51 ,  0.216, -0.755,  1.078, -0.647,
        1.078,  0.323])

In [74]:
np.round(np.mean(z), 3), np.round(np.std(z, ddof=0), 3)

(-0.0, 1.0)

In [76]:
z = 50 + 10 *(scores - np.mean(scores))/np.std(scores)
z

array([35.982, 65.097, 51.078, 34.903, 52.157, 42.452, 60.783, 43.53 ,
       60.783, 53.235])

In [78]:
np.mean(z)

50.0

In [79]:
np.std(z)

10.000000000000002

In [81]:
score_df['devlation value'] = z
score_df

score  devlation value
student                        
A           42           35.982
B           69           65.097
C           56           51.078
D           41           34.903
E           57           52.157
F           48           42.452
G           65           60.783
H           49           43.530
I           65           60.783
J           58           53.235

In [83]:
english_scores = np.array(df['english'])
english_scores

array([42, 69, 56, 41, 57, 48, 65, 49, 65, 58, 70, 47, 51, 64, 62, 70, 71,
       68, 73, 37, 65, 65, 61, 52, 57, 57, 75, 61, 47, 54, 66, 54, 54, 42,
       37, 79, 56, 62, 62, 55, 63, 57, 57, 67, 55, 45, 66, 55, 64, 66],
      dtype=int64)

In [84]:
df['english'].describe()

count   50.000
mean    58.380
std      9.800
min     37.000
25%     54.000
50%     57.500
75%     65.000
max     79.000
Name: english, dtype: float64

In [89]:
freq, _ = np.histogram(df['english'],bins=10, range=(0,100))

In [90]:
freq

array([ 0,  0,  0,  2,  8, 16, 18,  6,  0,  0], dtype=int64)

In [92]:
freq_class = [f'{i}-{i+10}' for i in range(0,100,10)]
freq_class

['0-10',
 '10-20',
 '20-30',
 '30-40',
 '40-50',
 '50-60',
 '60-70',
 '70-80',
 '80-90',
 '90-100']

In [96]:
freq_dist_df = pd.DataFrame({'frequency':freq},
                            index=pd.Index(freq_class, name='class'))
freq_dist_df

frequency
class            
0-10            0
10-20           0
20-30           0
30-40           2
40-50           8
50-60          16
60-70          18
70-80           6
80-90           0
90-100          0

In [97]:
class_value = [(i + (i+10))//2 for i in range(0, 100, 10)]
class_value

[5, 15, 25, 35, 45, 55, 65, 75, 85, 95]

In [98]:
rel_freq = freq / freq.sum()
rel_freq

array([0.  , 0.  , 0.  , 0.04, 0.16, 0.32, 0.36, 0.12, 0.  , 0.  ])

In [99]:
cum_rel_freq = np.cumsum(rel_freq)
cum_rel_freq

array([0.  , 0.  , 0.  , 0.04, 0.2 , 0.52, 0.88, 1.  , 1.  , 1.  ])